appId: any
---
- runFlow:
    file: open_drawer.yaml
- extendedWaitUntil:
    visible:
      id: "drawer_settings_btn"
    timeout: 5000
- tapOn:
    id: "drawer_settings_btn"
- waitForAnimationToEnd
- extendedWaitUntil:
    visible:
      id: "settings_screen"
    timeout: 5000
